常用的创建`error`对象的方法有以下两种，使用到了`Go`内置的`errors`和`fmt`库：

1. `errors.New()`：用于创建一个简单的错误，该错误只包含一个字符串消息。
2. `fmt.Errorf()`：用于创建一个带有格式化消息的错误，类似于`fmt.Sprintf`函数。

在`Go`语言中，我们通常在函数或者方法的最后一个参数返回`error`来表示执行过程中可能出现的的错误。如果发生了错误，函数将返回一个描述错误信息的`error`值。如果没有发生错误，则返回`nil`。在处理错误时，通常使用`if`语句来检查`error`是否为`nil`，若不为`nil`，则表示发生了错误，一般进行日志打印，并立即`return`。

一个简单的使用示例如下：

```go
func divide(x, y int) (int, error) {
    if y == 0 {
        return 0, errors.New("division by zero")
    }
    return x / y, nil
}

func main() {
    result, err := divide(10, 0)
    if err != nil {
        log.Printf("Error occurred: %v\n", err)
        return
    }
    fmt.Printf("Result: ", result)
}
```

在`Go`语言中，错误`error`也被定义为一种类型，它在`Go`代码里面是一个接口类型：

```go
type error interface {
	Error() string
}
```

这意味着，任何实现了`Error()`方法的结构体类型都可以作为错误类型。通过定义新的类型并实现`Error()`方法，可以创建更具针对性且携带更多信息的自定义错误类型，如下所示：

```go
type MyError struct {
	Code    int
	Msg     string
	Cause   error
	Created time.Time
}

// 建议使用指针接收器
func (e *MyError) Error() string {
	return fmt.Sprintf("Code: %d, Message: %s, Created: %s", e.Code, e.Msg, e.Created.Format("2006-01-02 15:04:05"))
}

func NewMyError(code int, msg string, cause error) error {
	return &MyError{
		Code:    code,
		Msg:     msg,
		Cause:   cause,
		Created: time.Now(),
	}
}

func FindUser(userId int) error {
	if userId != 123 {
		return NewMyError(500, fmt.Sprintf("user with ID %d not found", userId), nil)
	}
	return nil
}

func main() {
	err := FindUser(456)
	fmt.Println(err.Error())
}
```

标准库`errors`里还有`errors.Is`和`errors.As`这两个函数，它们的函数签名如下：

```go
func Is(err, target error) bool
func As(err error, target interface{}) bool
```

`errors.As`函数用来对`error`接口类型进行类型断言，以上面自定义的错误类型`MyError`为例：

```go
func main() {
	err := FindUser(456)
	fmt.Println(err.Error())
	myErr := &MyError{}
	if errors.As(err, &myErr) {
		fmt.Println("ok")
	}
	fmt.Println(myErr.Msg)
}
```

该代码将`error`类型转换为自定义错误类型`MyError`，从而可以通过`myErr`对象访问对应的字段和方法。

> **注意：**`errors.As`函数的第二个参数`target`不能是空指针，且必须是实现了`error`接口的类型的指针或接口。由于上面代码用`*MyError`实现了`error`接口，因此在`errors.As`中，参数需要传递`&myErr`，否则会报错`panic: errors: *target must be interface or implement error`。

对于`errors.Is`的使用，它用来判断的是两个错误是否是同一个对象，以下面代码为例：

```go
var customError = errors.New("自定义错误")

func main() {
	err := someFunction()
	if errors.Is(err, customError) {
		fmt.Println("遇到了自定义错误")
	} else {
		fmt.Println("遇到了其他错误")
	}
}

func someFunction() error {
	return customError
}
```

如果觉得`errors`库功能不够全面，可以使用下面这个第三方库，这是`errors`内置库的增强版：

```sh
go get github.com/pkg/errors
```

这里提供了`errors.Wrap`函数，用于在现有的错误上附加额外的上下文信息，形成一条调用链，相当于对原始错误的包装。

这个库还有其余用法，用的时候查阅一下即可。